export const SET_LOCATION = 'setLocation'
export const SET_ADDRESS = 'setAddress'
export const SET_ADDTOCART = 'setAddToCart'
export const SET_ADDCOUNTER = 'setAddCounter'
export const SET_DECREMENT = 'setDecrement'
export const DEL_FROMCART = 'delFromCart'